# Housing Data from Kaggle

In [1]:
import pandas as pd
import matplotlib.pyplot
import numpy as np

In [2]:
train_set = pd.read_csv("train.csv")

In [3]:
train_set.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [4]:
# train_set.info()

# Removing columns which have string and only keeping numeric columns

In [5]:
numeric_cols = train_set.select_dtypes(include=['number']).columns
train_set_numeric = train_set[numeric_cols]

In [6]:
train_set_numeric.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

# Finding Correlation 

In [7]:
corr_matrix = train_set_numeric.corr()

In [8]:
corr_matrix['SalePrice'].sort_values(ascending=False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
GarageYrBlt      0.486362
MasVnrArea       0.477493
Fireplaces       0.466929
BsmtFinSF1       0.386420
LotFrontage      0.351799
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePr

In [9]:
features_to_plot = ["SalePrice","OverallQual","GrLivArea","GarageCars","GarageArea","TotalBsmtSF","FullBath","TotRmsAbvGrd","YearBuilt","YearRemodAdd"]

In [10]:
# import pandas.plotting as plotting
# plotting.scatter_matrix(train_set_numeric[features_to_plot],figsize = (12,8))

In [11]:
train_set_numeric.plot(kind="scatter",x="SalePrice",y="GrLivArea")

<Axes: xlabel='SalePrice', ylabel='GrLivArea'>

In [12]:
train_set_numeric.plot(kind="scatter",x="SalePrice",y="OverallQual")

<Axes: xlabel='SalePrice', ylabel='OverallQual'>

In [13]:
final_train_set = train_set_numeric.drop("SalePrice",axis=1)
final_train_set_lables = train_set_numeric["SalePrice"].copy()

# Creating Imputer object 

In [14]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")
imputer.fit(final_train_set)
x = imputer.transform(final_train_set)

In [15]:
final_data = pd.DataFrame(x,columns=final_train_set.columns)
final_data.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1460.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    69.863699   10516.828082     6.099315   
std     421.610009    42.300571    22.027677    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    60.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    79.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.117123   443.639726  ...   
std       1.112799    30.202904     20.645407   180.731373   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   164.250000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        GarageArea   WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  \
count  1460.000000  1460.000000  1460.000000    1460.000000  1460.000000   
mean    472.980137    94.244521    46.660274      21.954110     3.409589   
std     213.804841   125.338794    66.256028      61.119149    29.317331   
min       0.000000     0.000000     0.000000       0.000000     0.000000   
25%     334.500000     0.000000     0.000000       0.000000     0.000000   
50%     480.000000     0.000000    25.000000       0.000000     0.000000   
75%     576.000000   168.000000    68.000000       0.000000     0.000000   
max    1418.000000   857.000000   547.000000     552.000000   508.000000   

       ScreenPorch     PoolArea       MiscVal       MoSold       YrSold  
count  1460.000000  1460.000000   1460.000000  1460.000000  1460.000000  
mean     15.060959     2.758904     43.489041     6.321918  2007.815753  
std      55.757415    40.177307    496.123024     2.703626     1.328095  
min       0.000000     0.000000      0.000000     1.000000  2006.000000  
25%       0.000000     0.000000      0.000000     5.000000  2007.000000  
50%       0.000000     0.000000      0.000000     6.000000  2008.000000  
75%       0.000000     0.000000      0.000000     8.000000  2009.000000  
max     480.000000   738.000000  15500.000000    12.000000  2010.000000  

[8 rows x 37 columns]

# Creating a Pipeline

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy = 'median'))
    ,('std_scaler',StandardScaler())  
])

In [17]:
final_data_to_be_pred = my_pipeline.fit_transform(final_train_set)

# Create Models

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor

model_1 = LogisticRegression()
model_2 = DecisionTreeRegressor()

model_1.fit(final_data_to_be_pred,final_train_set_lables)

LogisticRegression()

In [19]:
model_2.fit(final_data_to_be_pred,final_train_set_lables)

DecisionTreeRegressor()

# Testing model on small scale

In [20]:
some_data = final_train_set.iloc[0:5]
some_lables = final_train_set_lables.iloc[0:5]

some_prepared_data = my_pipeline.transform(some_data)

model_1.predict(some_prepared_data)

array([208500, 181500, 223500, 129500, 284000], dtype=int64)

In [21]:
model_2.predict(some_prepared_data)

array([208500., 181500., 223500., 140000., 250000.])

In [22]:
some_lables

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

# Evaluating the model

In [23]:
# from sklearn.model_selection import cross_val_score
# final_prepared_data = model_1.predict(final_data_to_be_pred)
# scores = cross_val_score(model_1,final_prepared_data,final_train_set_lables,scoring="neg_mean_squared_error",cv=10)
# rmsc_scores = np.sqrt(-scores)

from sklearn.metrics import mean_squared_error
final_prepared_data = model_1.predict(final_data_to_be_pred)
lin_mse = mean_squared_error(final_train_set_lables,final_prepared_data)
lin_rmsc = np.sqrt(lin_mse)

final_prepared_data = model_2.predict(final_data_to_be_pred)
tree_mse = mean_squared_error(final_train_set_lables,final_prepared_data)
tree_rmsc = np.sqrt(tree_mse)

In [24]:
lin_rmsc

13786.138175370612

In [25]:
final_prepared_data[:8]

array([208500., 181500., 223500., 140000., 250000., 143000., 307000.,
       200000.])

In [26]:
list(final_train_set_lables[:8])

[208500, 181500, 223500, 140000, 250000, 143000, 307000, 200000]

In [27]:
tree_rmsc

0.0

# passing test data

In [28]:
test_set = pd.read_csv("test.csv")
# # test_without_labels  = test_data.drop("SalePrice",axis=0)
# test_lables = test_data["SalePrice"].copy()

# test_set.describe()

In [29]:
# test_data.info()

In [30]:
test_numeric_cols = test_set.select_dtypes(include=['number']).columns
test_data = test_set[test_numeric_cols]

In [31]:
test_prepered_data = my_pipeline.fit_transform(test_data)
final_test_predications = model_1.predict(test_prepered_data)

In [32]:
list(final_test_predications[:10])

[144000,
 190000,
 175000,
 215000,
 192000,
 222500,
 194500,
 181000,
 260000,
 129500]